Repository Front-znad-zatoki/super-farmer, pull requests merged in 2021-02, with the labels that each got.

#70 Feature/#62 trade
  src/app/BreedProcessor.ts
  src/app/GameController.ts
  src/app/Trade.ts
  src/app/manuals/BreedPhaseDemo.ts
  src/app/manuals/TradeDemo.ts
  src/app/utils/ConvertToAnimalObject.ts
  test/Trade.spec.ts
Labels: SP 8, enhancement

#79 UI Component/#72 - WinModal
  src/app/components/ModalBasic.ts
  src/app/components/WinModal.ts
  src/app/manuals/WinModalDemo.ts
Labels: SP 3

#86 Feature/#68 implement process game 2
  src/app/GameController.ts
  src/app/View.ts
  src/app/logic/Game.ts
  src/app/logic/GameProcessor.ts
Labels: SP 8

#81 Feature/#80 trade modal
  src/app/Trade.ts
  src/app/components/EmptyModal.ts
  src/app/components/ModalBasic.ts
  src/app/components/TradeModal.ts
  src/app/manuals/TradeModalDemo.ts
  styles/components/_components.scss
  styles/components/_modal.scss
  styles/components/_tradeModal.scss
  tsconfig.json
Labels: feature

#105 Logic - Animal exchange
  src/app/GameController.ts
  src/app/Trade.ts
  src/app/ViewController.ts
  src/app/components/TradeModal.ts
  src/app/logic/Game.ts
  src/app/logic/GameProcessor.ts
  src/app/manuals/TradeDemo.ts
  src/app/manuals/TradeModalDemo.ts
  test/Trade.spec.ts
Labels: SP 3

#127 Refactor: trade modal callback
  src/Interfaces/CallbackNoParam.ts
  src/app/ViewController.ts
  src/app/components/TradeModal.ts
  src/app/manuals/TradeModalDemo.ts
Labels: refactor

#122 UI Component - Alert
  src/Enums/AlertEnum.ts
  src/app/components/Alert.ts
  src/app/manuals/AlertDemo.ts
  static/images/ui/critical.png
  static/images/ui/info.png
  static/images/ui/warn.png
Labels: SP 3, feature

#124 Add styling to WinModal
  index.html
  src/Animals/BigDog.ts
  src/Animals/Cow.ts
  src/Animals/Fox.ts
  src/Animals/Horse.ts
  src/Animals/Pig.ts
  src/Animals/Rabbit.ts
  src/Animals/Sheep.ts
  src/Animals/SmallDog.ts
  src/Animals/Wolf.ts
  src/app/Trade.ts
  src/app/components/WinModal.ts
  src/app/logic/defaultBankConfig.ts
  src/app/logic/defaultGameConfiguration.ts
  src/app/logic/mockGameConfiguration.ts
  src/app/logic/mockHerdConfig.ts
  src/app/manuals/PlayerPanelDemo.ts
  src/app/manuals/TradeModalDemo.ts
  src/app/manuals/WinModalDemo.ts
  src/app/manuals/herdManual.ts
  static/images/avatars/big_dog.svg
  static/images/avatars/cow.png
  static/images/avatars/cow.svg
  static/images/avatars/dog.png
  static/images/avatars/fox.png
  static/images/avatars/fox.svg
  static/images/avatars/horse.png
  static/images/avatars/horse.svg
  static/images/avatars/pig.png
  static/images/avatars/pig.svg
  static/images/avatars/rabbit.png
  static/images/avatars/rabbit.svg
  static/images/avatars/sheep.png
  static/images/avatars/sheep.svg
  static/images/avatars/small_dog.svg
  static/images/avatars/wolf.png
  static/images/avatars/wolf.svg
  static/images/ui/medal.svg
  styles/_global.scss
  styles/components/_modal.scss
Labels: SP 2, refactor

#126 Feature/#104 avatars colors
  src/Enums/AvatarsEnum.ts
  src/Enums/ColorsEnum.ts
  src/app/components/ModeModal.ts
  static/images/playerAvatars/farmer1.svg
  static/images/playerAvatars/farmer2.svg
  static/images/playerAvatars/farmer3.svg
  static/images/playerAvatars/farmer4.svg
  static/images/playerAvatars/man.svg
  static/images/playerAvatars/woman.svg
  styles/components/_modeModal.scss
Labels: feature

#121 Feature/landing page styling
  index.html
  src/app/MenuView.ts
  static/images/ui/background.png
  styles/App.scss
  styles/_global.scss
  styles/_variables.scss
  styles/components/_button.scss
  styles/components/_components.scss
  styles/components/_menu.scss
Labels: SP 5

#123 UI component - Alert styles
  src/Interfaces/CallbackNoParamInterface.ts
  src/app/components/Alert.ts
  src/app/components/TradeModal.ts
  src/app/components/WinModal.ts
  src/app/manuals/WinModalDemo.ts
  styles/components/_alert.scss
  styles/components/_components.scss
Labels: SP 2, feature

#129 Refactor - dice
  src/Interfaces/RandomAnimalInterface.ts
  src/app/BreedProcessor.ts
  src/app/Dice.ts
  src/app/DiceBuilder.ts
  src/app/FirstDice.ts
  src/app/GameController.ts
  src/app/SecondDice.ts
  src/app/components/WinModal.ts
  src/app/logic/Configuration.ts
  src/app/logic/Game.ts
  src/app/logic/GameProcessor.ts
  src/app/logic/Herd.ts
  src/app/manuals/BreedPhaseDemo.ts
Labels: refactor

#136 Style/#103 trade view
  src/app/components/TradeModal.ts
  src/app/logic/Bank.ts
  src/app/manuals/TradeModalDemo.ts
  static/images/ui/exchange-dark.svg
  static/images/ui/exchange.svg
  styles/components/_modal.scss
  styles/components/_tradeModal.scss
Labels: refactor

#137 Style/#111 bank
  src/app/components/BankBoard.ts
  styles/_global.scss
  styles/_variables.scss
  styles/components/_bankBoard.scss
  styles/components/_menu.scss
Labels: SP 2

#97 Implement trade heuristics fo AI Player
  src/app/AiPlayer.ts
  src/app/GameController.ts
  src/app/GameView.ts
  src/app/ViewController.ts
  src/app/components/PlayerPanel.ts
  src/app/logic/Game.ts
Labels: SP 8

#146 UI Component - Alert relations
  src/app/BreedProcessor.ts
  src/app/GameController.ts
  src/app/GameView.ts
  src/app/ViewController.ts
  src/app/components/TradeModal.ts
  src/app/logic/Game.ts
  src/app/logic/GameProcessor.ts
  src/app/manuals/BreedPhaseDemo.ts
  src/app/manuals/TradeModalDemo.ts
  styles/components/_tradeModal.scss
Labels: feature

#154 Hotfix - protect herd
  src/app/BreedProcessor.ts
  src/app/GameController.ts
  src/app/logic/GameProcessor.ts
Labels: fix

#156 Fix - change display of alert after turn is over
  src/app/logic/GameProcessor.ts
Labels: fix

#157 Hotfix - early end game
  src/app/GameController.ts
Labels: fix
