Repository Front-znad-zatoki/super-farmer, pull requests merged in 2021-01, with the labels that each got.

#23 Fix/css declaration order
  .prettierignore
  .stylelintrc.json
  package-lock.json
  package.json
  src/app/App.ts
  styles/App.scss
Labels: duplicate, enhancement

#26 added base husky config, fixed App.ts
  .huskyrc
  package-lock.json
  package.json
  src/app/App.ts
Labels: enhancement

#12 feature/#2 create class Player
  src/Herd.ts
  src/Player.ts
Labels: enhancement

#14 Feature/#13 animals
  src/Animals/Animal.ts
  src/Animals/BigDog.ts
  src/Animals/Cow.ts
  src/Animals/Fox.ts
  src/Animals/Horse.ts
  src/Animals/Pig.ts
  src/Animals/Rabbit.ts
  src/Animals/Sheep.ts
  src/Animals/SmallDog.ts
  src/Animals/Wolf.ts
  src/Enums/AnimalNamesEnum.ts
  src/Enums/AnimalRolesEnum.ts
  src/Interfaces/AttackHerdInterface.ts
  src/Interfaces/ProtectHerdInterface.ts
  test/animal.spec.ts
  test/bigDog.spec.ts
  test/fox.spec.ts
  test/smallDog.spec.ts
  test/wolf.spec.ts
Labels: enhancement

#30 Feature/#21 avatar and variables
  .env
  index.html
  jest.config.json
  resources/images/avatars/cow.png
  resources/images/avatars/dog.png
  resources/images/avatars/fox.png
  resources/images/avatars/horse.png
  resources/images/avatars/pig.png
  resources/images/avatars/rabbit.png
  resources/images/avatars/sheep.png
  resources/images/avatars/wolf.png
  resources/images/ui/favicon.png
  src/app/App.ts
Labels: SP 1

#28 Feature/#10 remaining time
  src/app/Timer.ts
  test/Timer.spec.ts
Labels: SP 3

#39 Feature/#23 process breed
  src/Herd.ts
  src/Player.ts
  src/app/BreedProcessor.ts
  src/app/Dice.ts
  src/app/FirstDice.ts
  src/app/SecondDice.ts
Labels: BLOCKER, SP 8

#61 Feature/#22-game-controller
  src/app/BreedProcessor.ts
  src/app/GameController.ts
  src/app/Timer.ts
  src/app/View.ts
  test/Timer.spec.ts
Labels: SP 8

#65 Release 0.1
  .env
  index.html
  jest.config.json
  package-lock.json
  package.json
  src/Animals/Animal.ts
  src/Animals/BigDog.ts
  src/Animals/Cow.ts
  src/Animals/Fox.ts
  src/Animals/Horse.ts
  src/Animals/Pig.ts
  src/Animals/Rabbit.ts
  src/Animals/Sheep.ts
  src/Animals/SmallDog.ts
  src/Animals/Wolf.ts
  src/Enums/AnimalNamesEnum.ts
  src/Enums/AnimalRolesEnum.ts
  src/Interfaces/AttackHerdInterface.ts
  src/Interfaces/DiceInterface.ts
  src/Interfaces/ProtectHerdInterface.ts
  src/Player.ts
  src/app/App.ts
  src/app/BreedProcessor.ts
  src/app/Dice.ts
  src/app/FirstDice.ts
  src/app/GameController.ts
  src/app/SecondDice.ts
  src/app/Timer.ts
  src/app/View.ts
  src/app/logic/Herd.ts
  src/app/utils/Render.ts
  src/index.ts
  static/Maps/Roadmap.png
  static/Maps/Sprint01/Flow-sprint1.jpg
  static/Maps/Sprint01/Roadmap-sprint1.png
  static/images/avatars/cow.png
  static/images/avatars/dog.png
  static/images/avatars/fox.png
  static/images/avatars/horse.png
  static/images/avatars/pig.png
  static/images/avatars/rabbit.png
  static/images/avatars/sheep.png
  static/images/avatars/wolf.png
  static/images/ui/favicon.png
  styles/App.scss
  styles/_global.scss
  styles/components/_components.scss
  styles/components/_view.scss
  test/Timer.spec.ts
  test/animal.spec.ts
  test/bigDog.spec.ts
  test/fox.spec.ts
  test/herd.spec.ts
  test/render.spec.ts
  test/smallDog.spec.ts
  test/wolf.spec.ts
  tsconfig.json
Labels: v0.1

#60 Feature/#58 #59 improvements
  src/Animals/Animal.ts
  src/Animals/BigDog.ts
  src/Animals/Cow.ts
  src/Animals/Fox.ts
  src/Animals/Horse.ts
  src/Animals/Pig.ts
  src/Animals/Rabbit.ts
  src/Animals/Sheep.ts
  src/Animals/SmallDog.ts
  src/Animals/Wolf.ts
  src/app/App.ts
  src/app/utils/Render.ts
  test/animal.spec.ts
Labels: bug, enhancement

#71 Feature/#48 #49 bank player score
  src/Player.ts
  src/app/logic/Bank.ts
Labels: enhancement
